### ISSUE TITLE
Does not work with 2.2

### ISSUE THREAD

**Issue by throwable-one** [jonasundderwolf/django-image-cropping#133]
Widget API changed:
`"render() got an unexpected keyword argument 'renderer'"`

**Comment by throwable-one** [comment]
Seems to be fixed in master

**Comment by anrie** [comment]
If it is working on the `master` branch, it should also work with version 1.2.
