### ISSUE TITLE
Uncaught TypeError: $(...).Jcrop is not a function in Django 2.2.14

### ISSUE THREAD

**Issue by bmihelac** [jonasundderwolf/django-image-cropping#155]
After upgrading Django from 2.1.X to 2.2.14 following error occurs in admin:

```
jquery.js:4055 Uncaught TypeError: $(...).Jcrop is not a function
    at HTMLInputElement.<anonymous> (image_cropping.js:88)
    at Function.each (jquery.js:381)
    at jQuery.fn.init.each (jquery.js:203)
    at Object.init (image_cropping.js:4)
    at HTMLDocument.<anonymous> (image_cropping.js:197)
    at mightThrow (jquery.js:3762)
    at process (jquery.js:3830)
```

I noticed that jCrop is initialized to `django.jQuery`, instead to `jQ`

Anyone have similar issue?

![2020-08-07_09-37](https://user-images.githubusercontent.com/13813/89621491-b367c000-d891-11ea-967c-8f369a29d0fd.png)

**Comment by anrie** [comment]
Hey @bmihelac,

this looks familiar to Issue #140 and is probably related to the [new way of merging assets in Django 2.2.](https://docs.djangoproject.com/en/3.0/releases/2.2/#merging-of-form-media-assets): 

Could you please check if the issue also arises when using [this branch](https://github.com/jonasundderwolf/django-image-cropping/pull/148)?

**Comment by bmihelac** [comment]
@anrie thanks for answer, I'll check it asap

**Comment by bmihelac** [comment]
@anrie I have tested your branch and it works.

**Comment by bmihelac** [comment]
I'm closing this issue as it is fixed with https://github.com/jonasundderwolf/django-image-cropping/commit/e66c090071ded75f7c2578e8d9e7d48642c5a4ad
