### ISSUE TITLE
Doesn't work with django 1.9b1.

### ISSUE THREAD

**Issue by Dharmik8478** [jonasundderwolf/django-image-cropping#80]
I am updating my project to 1.9b1 and while updating i am facing this error

  File "/opt/pyvirtual/py_3.4-dj_1.9/lib/python3.4/site-packages/image_cropping/__init__.py", line 1, in <module>
    from .fields import ImageRatioField, ImageCropField
  File "/opt/pyvirtual/py_3.4-dj_1.9/lib/python3.4/site-packages/image_cropping/fields.py", line 5, in <module>
    from .widgets import ImageCropWidget
  File "/opt/pyvirtual/py_3.4-dj_1.9/lib/python3.4/site-packages/image_cropping/widgets.py", line 4, in <module>
    from django.db.models import get_model, ObjectDoesNotExist
ImportError: cannot import name 'get_model'

so please provide me solution for this or any alternative.

**Comment by shacker** [comment]
Under Django 1.9rc1, it fails with

`django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

(just using the basic/starter tutorial instructions).

**Comment by Dharmik8478** [comment]
I have same error on django 1.9rc1

**Comment by fritz-k** [comment]
`django.core.exceptions.AppRegistryNotReady` masks the original exception.
Try running `runserver` with `--noreload` option (see https://code.djangoproject.com/ticket/25634 for details).
Also, same problem for me.

**Comment by anrie** [comment]
We haven't switched to 1.9 yet and are quite busy at the moment so we didn't have the chance to examine this closer.

I opened a Django 1.9 branch (https://github.com/jonasundderwolf/django-image-cropping/tree/django-19) and fixed the glaring issues. The example project seems to run now, however the tests are still failing. If anyone fixes the remaining issues, we're glad to see a PR.

**Comment by fritz-k** [comment]
Thanks for the quick fixes!
django-webtest added Django 1.9 compatibility with 1.7.8. https://github.com/jonasundderwolf/django-image-cropping/pull/81 should fix this issue.

**Comment by Dharmik8478** [comment]
Ok great, thanks for fixing it...
